### ISSUE TITLE
Not start on phpstorm

### ISSUE THREAD

**Issue by Delimer** [Microsoft/vso-intellij#10]
```
Plugin 'com.microsoft.vso.idea' failed to initialize and will be disabled.  Please restart PhpStorm.

java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
    at com.microsoft.alm.plugin.idea.setup.ApplicationStartup.<clinit>(ApplicationStartup.java:22)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.a(ComponentManagerImpl.java:427)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.a(ComponentManagerImpl.java:417)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.access$000(ComponentManagerImpl.java:403)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:108)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:87)
    at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:101)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:499)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:481)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:170)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:62)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:702)
    at java.awt.EventQueue$3.run(EventQueue.java:696)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:362)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory PluginClassLoader[com.microsoft.vso.idea, 0.95.0]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 28 more
```

**Comment by madhurig** [comment]
What version of PhpStorm are you using? We support PhpStorm versions 9 and 10. If you are using an older version, it may not work. 
It also looks like you are using an older version of our plugin, we changed our plugin to com.microsoft.alm.*, could you please try upgrading to the latest version? 

Regards,
Madhuri

**Comment by Delimer** [comment]
phpStorm 9.0.2

**Comment by madhurig** [comment]
Hi Delimer, 

It looks like PhpStorm 9.0.2 is not packaging the logger jars the plugin depends on. I will look into why they are not available and how we can avoid this in the plugin. 

As a workaround you could try copying the jars from the IntelliJ community edition install to the PhpStorm install lib folder. On my machine I copied **slf4j-api-1.7.10.jar ** and **slf4j-log4j12-1.7.10** to C:\Program Files (x86)\JetBrains\PhpStorm 9.0.2\lib. Then enable the plugin and restart PhpStorm.
Instead of installing the IntelliJ community edition, you can download the jars from: http://www.slf4j.org/dist/ if that is more convenient for you.

Thanks for reporting the issue and sorry for the inconvenience.
-Madhuri

**Comment by Delimer** [comment]
Thank you. Now it works.

**Comment by madhurig** [comment]
@Delimer : Thanks for trying out the workaround and glad you are unblocked.
