### ISSUE TITLE
Edit workspace Issue

### ISSUE THREAD

**Issue by arafeh94** [Microsoft/vso-intellij#106]
I want to change my workspace mapping so I opened from vcs->tfvc->edit workspace
all mapping are empty
and android studio show this error in log : 

> 2017-09-14 12:53:43,957 [ 463341]   INFO - alm.plugin.external.ToolRunner - arguments: @ 
> 2017-09-14 12:53:44,434 [ 463818]   INFO - ugin.external.commands.Command - ERROR: An argument error occurred: The workspace could not be determined from any argument paths or the current working directory. 
> 2017-09-14 12:53:44,435 [ 463819]   INFO - ugin.external.commands.Command - CMD: Team Explorer Everywhere Command Line Client (version 14.123.1.201709051449) 
> 2017-09-14 12:53:44,435 [ 463819]   INFO - ugin.external.commands.Command - CMD:  
> 2017-09-14 12:53:44,436 [ 463820]   INFO - ugin.external.commands.Command - CMD:  workfold command: 
> 2017-09-14 12:53:44,436 [ 463820]   INFO - ugin.external.commands.Command - CMD:  
> 2017-09-14 12:53:44,437 [ 463821]   INFO - ugin.external.commands.Command - CMD:   Creates, modifies, or displays information about the mappings between your 
> 2017-09-14 12:53:44,437 [ 463821]   INFO - ugin.external.commands.Command - CMD:   workspace folders and the source control server folders to which they 
> 2017-09-14 12:53:44,437 [ 463821]   INFO - ugin.external.commands.Command - CMD:   correspond. 
> 2017-09-14 12:53:44,437 [ 463821]   INFO - ugin.external.commands.Command - CMD:  
> 2017-09-14 12:53:44,437 [ 463821]   INFO - ugin.external.commands.Command - CMD:  Valid option sets: 
> 2017-09-14 12:53:44,437 [ 463821]   INFO - ugin.external.commands.Command - CMD:  
> 2017-09-14 12:53:44,451 [ 463835]   INFO - ugin.external.commands.Command - CMD:   workfold /cloak [/collection:<url>] [/workspace:<value>] 
> 2017-09-14 12:53:44,451 [ 463835]   INFO - ugin.external.commands.Command - CMD:            <serverFolder>|<localFolder> 
> 2017-09-14 12:53:44,451 [ 463835]   INFO - ugin.external.commands.Command - CMD:   workfold /decloak [/collection:<url>] [/workspace:<value>] 
> 2017-09-14 12:53:44,451 [ 463835]   INFO - ugin.external.commands.Command - CMD:            <serverFolder>|<localFolder> 
> 2017-09-14 12:53:44,451 [ 463835]   INFO - ugin.external.commands.Command - CMD:   workfold /unmap [/collection:<url>] [/workspace:<value>] 
> 2017-09-14 12:53:44,451 [ 463835]   INFO - ugin.external.commands.Command - CMD:            <serverFolder>|<localFolder> 
> 2017-09-14 12:53:44,451 [ 463835]   INFO - ugin.external.commands.Command - CMD:   workfold [/collection:<url>] [/workspace:<value>] <serverFolder> 
> 2017-09-14 12:53:44,451 [ 463835]   INFO - ugin.external.commands.Command - CMD:   workfold [/map] [/collection:<url>] [/workspace:<value>] <serverFolder> 
> 2017-09-14 12:53:44,452 [ 463836]   INFO - ugin.external.commands.Command - CMD:            <localFolder> 
> 2017-09-14 12:53:44,452 [ 463836]   INFO - ugin.external.commands.Command - CMD:   workfold [/workspace:<value>] 
> 2017-09-14 12:53:44,452 [ 463836]   INFO - ugin.external.commands.Command - CMD:   workfold <localFolder> 
> 2017-09-14 12:53:44,452 [ 463836]   INFO - ugin.external.commands.Command - CMD:  
> 2017-09-14 12:53:44,469 [ 463853]   WARN - ugin.external.commands.Command - CMD: parsing output failed 

java.lang.RuntimeException: An argument error occurred: The workspace could not be determined from any argument paths or the current working directory.

	at com.microsoft.alm.plugin.external.commands.Command.throwIfError(Command.java:402)
	at com.microsoft.alm.plugin.external.commands.FindWorkspaceCommand.throwIfError(FindWorkspaceCommand.java:132)
	at com.microsoft.alm.plugin.external.commands.FindWorkspaceCommand.parseOutput(FindWorkspaceCommand.java:88)
	at com.microsoft.alm.plugin.external.commands.FindWorkspaceCommand.parseOutput(FindWorkspaceCommand.java:24)
	at com.microsoft.alm.plugin.external.commands.Command$1.completed(Command.java:171)
	at com.microsoft.alm.plugin.external.ToolRunner$ListenerProxy.completed(ToolRunner.java:295)
	at com.microsoft.alm.plugin.external.ToolRunner$ProcessWaiter.run(ToolRunner.java:333)

> 2017-09-14 12:53:44,470 [ 463854]   INFO - ugin.external.commands.Command - 513392178(ns) - elapsed time for workfold -noprompt ******** 
> 2017-09-14 12:53:44,470 [ 463854]   WARN - in.idea.common.utils.VcsHelper - Unable to get repository context for the project. 
> java.lang.RuntimeException: An argument error occurred: The workspace could not be determined from any argument paths or the current working directory.

	at com.microsoft.alm.plugin.external.commands.Command.throwIfError(Command.java:402)
	at com.microsoft.alm.plugin.external.commands.FindWorkspaceCommand.throwIfError(FindWorkspaceCommand.java:132)
	at com.microsoft.alm.plugin.external.commands.FindWorkspaceCommand.parseOutput(FindWorkspaceCommand.java:88)
	at com.microsoft.alm.plugin.external.commands.FindWorkspaceCommand.parseOutput(FindWorkspaceCommand.java:24)
	at com.microsoft.alm.plugin.external.commands.Command$1.completed(Command.java:171)
	at com.microsoft.alm.plugin.external.ToolRunner$ListenerProxy.completed(ToolRunner.java:295)
	at com.microsoft.alm.plugin.external.ToolRunner$ProcessWaiter.run(ToolRunner.java:333)

> 2017-09-14 12:53:44,470 [ 463854]   INFO - in.idea.common.utils.VcsHelper - getRepositoryContext: We couldn't determine the VCS provider, so returning null. 
> 2017-09-14 12:53:44,470 [ 463854]   WARN - vc.ui.workspace.WorkspaceModel - loadWorkspace: Could not determine repositoryContext for project 
> 2017-09-14 12:53:44,472 [ 463856]   INFO - vc.ui.workspace.WorkspaceModel - loadWorkspace: done loading

**Comment by arafeh94** [comment]
![capture](https://user-images.githubusercontent.com/5004409/30426475-deccf03c-9954-11e7-89f1-32c2d6731b1b.PNG)
![capture2](https://user-images.githubusercontent.com/5004409/30426476-def28004-9954-11e7-85e6-a211874c13c5.PNG)

**Comment by mems** [comment]
I have a same issue, where both "Workspace Properties" and "Configuration Managment" fields are empty: no workspace infos like server, owner, computer and no repository listed
