### ISSUE TITLE
Authentication passed, but can't get repository from TFS!

### ISSUE THREAD

**Issue by Gavineil** [Microsoft/vso-intellij#113]
2017-10-25 08:33:44,589 [ 398751]   INFO - tion.TfsAuthenticationProvider - starting TfsAuthenticator 
2017-10-25 08:33:44,589 [ 398751]   INFO - tion.TfsAuthenticationProvider - Async authentication starting 
2017-10-25 08:33:51,645 [ 405807]   INFO - .services.HttpProxyServiceImpl - useHttpProxy: false 
2017-10-25 08:33:51,901 [ 406063]  DEBUG - n.telemetry.TfsTelemetryHelper - sendEvent(TfsConnection, {VSO.Plugin.Property.Success=true, TFS.Version=TFS2015_or_later}) 
2017-10-25 08:33:51,901 [ 406063]   INFO - tion.TfsAuthenticationProvider - Async authentication done - result: true 
2017-10-25 08:33:51,901 [ 406063]   INFO - on.ServerContextLookupListener - loadContexts activeOperation with 1 contexts and a scope of REPOSITORY 
2017-10-25 08:33:51,901 [ 406063]   INFO - on.ServerContextLookupListener - loadContexts terminateActiveOperation in state NOT_STARTED 
2017-10-25 08:33:51,901 [ 406063]   INFO - on.ServerContextLookupListener - ServerContext operation terminated 
2017-10-25 08:33:51,901 [ 406063]   INFO - on.ServerContextLookupListener - ServerContext lookup started 
2017-10-25 08:33:51,917 [ 406079]   WARN - s.ServerContextLookupOperation - doWork: Unable to do lookup on context: https://itech/Demo/Test/_git/demo 
2017-10-25 08:33:51,917 [ 406079]   WARN - s.ServerContextLookupOperation - doWork: Exception 
java.lang.NullPointerException
	at com.microsoft.alm.common.utils.UrlHelper.resolveEndpointUri(UrlHelper.java:361)
	at com.microsoft.alm.plugin.context.soap.CatalogServiceImpl.<init>(CatalogServiceImpl.java:72)
	at com.microsoft.alm.plugin.context.soap.SoapServicesImpl.getCatalogService(SoapServicesImpl.java:19)
	at com.microsoft.alm.plugin.operations.ServerContextLookupOperation.doSoapCollectionLookup(ServerContextLookupOperation.java:165)
	at com.microsoft.alm.plugin.operations.ServerContextLookupOperation$1.run(ServerContextLookupOperation.java:76)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2017-10-25 08:33:51,917 [ 406079]   INFO - on.ServerContextLookupListener - ServerContext lookup results has error: true 
2017-10-25 08:33:51,917 [ 406079]   INFO - on.ServerContextLookupListener - ServerContext lookup completed 
2017-10-25 08:33:51,917 [ 406079]   INFO - on.ServerContextLookupListener - ServerContext operation done

**Comment by ForNeVeR** [comment]
@marco-augustin, hello. Could you please show a server URL you're trying to use? From the screenshot of the opening post, it looks like the server URL isn't right: actual server URL shouldn't include `_git`; most likely the right one would be `https://itech/Demo` for this particular example.

**Comment by marco-augustin** [comment]
It works now. Thanks for the hint! The original server address had the collection name in the URL.

**Comment by ForNeVeR** [comment]
Thanks for your answer. We have plans to improve this UI to make it easier to enter the right URL there.
