### ISSUE TITLE
Unable to access plugin - Authentication error

### ISSUE THREAD

**Issue by JoWerk** [Microsoft/vso-intellij#114]
TFS:
Microsoft Visual Studio Team Foundation Server
Version 15.117.26714.0

IntelliJ
Ultimate 2017.2.5

Git
2.14.1.windows.1

TFS plugin
1.125

It appears as though I am unable to authenticate to the remote repository.  After upgrading to this version I had troubles connecting to the repository.  I have since tried to reimport my project from TFS and was able to import the project but was unable to connect to TFS via the plugin.

I received the error below when trying to import and login to tfs.
WARN - n.context.ServerContextManager - checkTfsVersionAndConnection: 404 while trying to connect to server so either bad url or unsupported server version 
2017-11-01 16:07:27,588 [ 201928]   INFO - tion.TfsAuthenticationProvider - Async authentication done - result: false 
2017-11-01 16:07:27,588 [ 201928]  DEBUG - n.telemetry.TfsTelemetryHelper - sendEvent(TfsConnection, {VSO.Plugin.Property.Success=false, TFS.Version=TFS2012_or_older}) 
2017-11-01 16:07:27,590 [ 201930]  ERROR - ugin.authentication.AuthHelper - getAuthenticationInfoSynchronously: failed to get authentication info from user 
2017-11-01 16:07:27,591 [ 201931]   WARN - ugin.authentication.AuthHelper - getAuthenticationInfoSynchronously 
java.util.concurrent.ExecutionException: com.microsoft.alm.plugin.exceptions.TeamServicesException: KEY_TFS_UNSUPPORTED_VERSION
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:476)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:380)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:84)
	at com.microsoft.alm.plugin.authentication.AuthHelper.getAuthenticationInfoSynchronously(AuthHelper.java:79)
	at com.microsoft.alm.plugin.context.ServerContextManager.updateAuthenticationInfo(ServerContextManager.java:603)
	at com.microsoft.alm.plugin.idea.git.extensions.TfGitHttpAuthDataProvider.forgetPassword(TfGitHttpAuthDataProvider.java:72)
	at git4idea.commands.GitHttpGuiAuthenticator.forgetPassword(GitHttpGuiAuthenticator.java:197)
	at git4idea.commands.GitHandler$1.processTerminated(GitHandler.java:542)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:99)
	at com.intellij.util.EventDispatcher.access$200(EventDispatcher.java:35)
	at com.intellij.util.EventDispatcher$2.invoke(EventDispatcher.java:79)
	at com.sun.proxy.$Proxy118.processTerminated(Unknown Source)
	at git4idea.commands.GitTextHandler$1.processTerminated(GitTextHandler.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.execution.process.ProcessHandler$4.invoke(ProcessHandler.java:227)
	at com.sun.proxy.$Proxy16.processTerminated(Unknown Source)
	at com.intellij.execution.process.ProcessHandler$3.run(ProcessHandler.java:184)
	at com.intellij.execution.process.ProcessHandler$TasksRunner.execute(ProcessHandler.java:260)
	at com.intellij.execution.process.ProcessHandler.notifyTerminated(ProcessHandler.java:165)
	at com.intellij.execution.process.ProcessHandler.notifyProcessTerminated(ProcessHandler.java:161)
	at com.intellij.execution.process.KillableProcessHandler.notifyProcessTerminated(KillableProcessHandler.java:134)
	at com.intellij.execution.process.BaseOSProcessHandler.onOSProcessTerminated(BaseOSProcessHandler.java:192)
	at com.intellij.execution.process.OSProcessHandler.onOSProcessTerminated(OSProcessHandler.java:92)
	at com.intellij.execution.process.BaseOSProcessHandler$2$1.consume(BaseOSProcessHandler.java:155)
	at com.intellij.execution.process.BaseOSProcessHandler$2$1.consume(BaseOSProcessHandler.java:140)
	at com.intellij.execution.process.ProcessWaitFor$1.run(ProcessWaitFor.java:62)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.microsoft.alm.plugin.exceptions.TeamServicesException: KEY_TFS_UNSUPPORTED_VERSION
	at com.microsoft.alm.plugin.context.ServerContextManager.checkTfsVersionAndConnection(ServerContextManager.java:314)
	at com.microsoft.alm.plugin.context.ServerContextManager.validateServerConnection(ServerContextManager.java:231)
	at com.microsoft.alm.plugin.context.ServerContextManager.validateServerConnection(ServerContextManager.java:195)
	at com.microsoft.alm.plugin.idea.common.services.CredentialsPromptImpl.validateCredentials(CredentialsPromptImpl.java:68)

**Comment by scottieGGGG** [comment]
We are having similar (if not the exact same issue)... TFS 2017 (pre-updates) was working fine with the plug in.. .but went through an upgrade round.. both to TFS 2017.. as well as plug in.  During that, we switched to SSL on TFS.. and since that change... not able to connection to TFS 2017 git repositories within plugin.

TFS alone works well... and even git via command line calls works with repositories on the updated TFS site... only the plug in is failing to authenticate.  :(
