### ISSUE TITLE
Local TFS - "HTTP 401 Unauthorized" when getting history

### ISSUE THREAD

**Issue by ivmreg** [Microsoft/vso-intellij#115]
Hello, 
I am trying to use the TFVC plugin (1.125) for one of JetBrains applications: PyCharm.
TFVC command line utilities (14.123.1) were downloaded from here:
https://github.com/Microsoft/team-explorer-everywhere/releases
I have installed the plugin as well and enabled VCS integration for the project, selecting TFVC.
When I'm trying to view the history of changes (or run any other command) I get the following error:
```
HTTP 401 Unauthorized
javax.ws.rs.NotAuthorizedException: HTTP 401 Unauthorized
	at com.microsoft.alm.plugin.idea.tfvc.core.TFSVcs.getServerContext(TFSVcs.java:277)
	at com.microsoft.alm.plugin.idea.tfvc.core.TFSFileListener$1.run(TFSFileListener.java:78)

```

**Comment by ivmreg** [comment]
Re-doing the process from scratch fixed the issue
