### ISSUE TITLE
Login not possible

### ISSUE THREAD

**Issue by derchris** [Microsoft/vso-intellij#14]
When trying to login via Team Services it shows the OAuth Webview, I can login with my credentials, UI jumps back to Login, then moves - for a short time - on to "Project overview" but than returns back to the Appcode Loginscreen showing AssertionError.

**Comment by leantk** [comment]
Hi,

I'm sorry to hear about your problem. Thanks for bringing it to our attention. Could you do me a favor and turn on debug logging for our plugin and send me a log generated from a run where you try to log in and it fails? The instructions on how to do this are below. 

Instructions for Logging:
Under the Help menu, Debug Log Settings, add a value of “com.microsoft.alm” (without the double quotes) and click OK. Then, repro the issue. The log file should have a bunch of references to “com.microsoft.alm” (which is a prefix of our Java packages). If you could attach all of the log files that have references to those, it’d be a big help. The logs can be found if you go to the Help menu and select View Log in Finder.

**Comment by derchris** [comment]
Thanks for the quick replying... please find log attached

[idea.log.txt](https://github.com/Microsoft/vso-intellij/files/261474/idea.log.txt)


<img width="515" alt="bildschirmfoto 2016-05-12 um 16 08 18" src="https://cloud.githubusercontent.com/assets/598608/15217418/c7dbcacc-185b-11e6-9104-5125b907a6b7.png">

**Comment by leantk** [comment]
That log doesn't seem to contain any reference to an AssertionError which is weird. Would you be able to look in any of the logs over the past day that have been saved off and search for "java.lang.AssertionError" and see if that is contained in any of them please? There should be a stack trace that is accompanied with the error that will point us in the right direction.

**Comment by leantk** [comment]
Also if you don't feel comfortable adding your logs or any other information here, feel free to email me at leantk@microsoft.com

**Comment by derchris** [comment]
I checked the whole day's log and didn't find any assertion errors :(

But I found some authentication errors, which I'll send by mail

For further reference here's the snippet:
```
WARN - in.idea.ui.common.LookupHelper - Authenticating with Team Services failed 
com.microsoft.alm.plugin.context.rest.VstsHttpClient$VstsHttpClientException: Unauthorized
	at com.microsoft.alm.plugin.context.rest.VstsHttpClient.sendRequest(VstsHttpClient.java:34)
	at com.microsoft.alm.plugin.context.ServerContextManager.checkVstsConnection(ServerContextManager.java:203)
	at com.microsoft.alm.plugin.context.ServerContextManager.validateServerConnection(ServerContextManager.java:191)
	at com.microsoft.alm.plugin.authentication.VsoAuthenticationProvider$1.onSuccess(VsoAuthenticationProvider.java:78)
	at com.microsoft.alm.plugin.authentication.VsoAuthenticationProvider$1.onSuccess(VsoAuthenticationProvider.java:65)
	at com.google.common.util.concurrent.Futures$6.run(Futures.java:1319)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457)
	at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
	at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185)
	at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:53)
	at com.microsoft.alm.plugin.authentication.facades.VsoAuthInfoProvider$1.run(VsoAuthInfoProvider.java:126)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2016-05-12 10:28:39,632 [ 336749]  ERROR - s.ServerContextLookupOperation - doWork: Unable to do lookup on context: https://XY.visualstudio.com 
2016-05-12 10:28:39,632 [ 336749]   WARN - s.ServerContextLookupOperation - doWork: Exception 
com.microsoft.alm.client.model.VssResourceNotFoundException: API resource location 8031090f-ef1d-4af6-85fc-698cd75d42bf is not registered on https://XY.visualstudio.com. HTTP 401 Unauthorized
```

**Comment by leantk** [comment]
Many AssertionErrors in the authentication have been removed and replaced with exceptions to create better trace-ability for issues like this. If you upload the new 0.101.0 version of the plugin you most likely will see a different error that will help us pinpoint the underlying problem better.

**Comment by jpricketMSFT** [comment]
Hi derchris,

Did you have a chance to try the latest update? Any more information?

Thanks,
Jason

**Comment by jpricketMSFT** [comment]
Closing this issue due to no response. If you are still having issues, please let us know.
