### ISSUE TITLE
Cannot config tfvc setting

### ISSUE THREAD

**Issue by criminalistJong** [Microsoft/vso-intellij#156]
I use Rider 
and set TF executable path to Tool path("TEE-CLC-XX\tf") and click test
but occurred error As follows
how to resolve this problem
---------------------
Picked up JAVA_TOOL_OPTIONS: -Djava.net.preferIPv4Stack=true
Picked up _JAVA_OPTIONS: -Xmx1024M 

java.lang.RuntimeException: Picked up JAVA_TOOL_OPTIONS: -Djava.net.preferIPv4Stack=true
Picked up _JAVA_OPTIONS: -Xmx1024M 

	at com.microsoft.alm.plugin.external.commands.Command.throwIfError(Command.java:402)
	at com.microsoft.alm.plugin.external.commands.TfVersionCommand.parseOutput(TfVersionCommand.java:31)
	at com.microsoft.alm.plugin.external.commands.TfVersionCommand.parseOutput(TfVersionCommand.java:15)
	at com.microsoft.alm.plugin.external.commands.Command$1.completed(Command.java:171)
	at com.microsoft.alm.plugin.external.ToolRunner$ListenerProxy.completed(ToolRunner.java:295)
	at com.microsoft.alm.plugin.external.ToolRunner$ProcessWaiter.run(ToolRunner.java:333)
---------------------

**Comment by whoisj** [comment]
@mfilippov I believe I'm seeing this too, with both latest and the builds from master.

![image](https://user-images.githubusercontent.com/11578325/43654988-35215788-971b-11e8-9ba1-3d5514cbec31.png)

Any suggestions?

**Comment by mfilippov** [comment]
@whoisj I started an investigation of the problem.

**Comment by mfilippov** [comment]
Fixed in PR #163

**Comment by whoisj** [comment]
This issue has been resolved, and an updated (fixed) plug-in published.
