### ISSUE TITLE
Unable to push to VSTS

### ISSUE THREAD

**Issue by columan** [Microsoft/vso-intellij#18]
Hi,
when I try to push some changes to my git repo on VSTS, authorization fails. I enter only my mail address and than I'm forwarded to a live login page, where I login with my credentials. Than I'm back in IntelliJ and after some seconds I'm asked again to login.

I have attached the logs.

Thx
Tim

```
2016-06-27 22:49:26,360 [  21830]   INFO - lij.diagnostic.DebugLogManager - Set DEBUG for the following categories: “com.microsoft.alm 
2016-06-27 22:50:12,005 [  67475]   INFO -  #git4idea.commands.GitHandler - [ng2-crud-app] git -c core.quotepath=false push --progress --porcelain origin refs/heads/master:master 
2016-06-27 22:50:20,703 [  76173]   INFO - ugin.authentication.AuthHelper - getAuthenticationInfoSynchronously calling authenticateAsync on https://xxxvisualstudio.com 
2016-06-27 22:50:20,724 [  76194]   INFO - .auth.pat.VstsPatAuthenticator - Signing out from uri: https://app.vssps.visualstudio.com 
2016-06-27 22:50:20,740 [  76210]   INFO - m.provider.JaxrsClientProvider - Getting a jaxrs client that works across multiple accounts. 
2016-06-27 22:50:20,742 [  76212]   INFO - auth.oauth.OAuth2Authenticator - Using oauth2-useragent providers to retrieve AAD token. 
2016-06-27 22:50:41,761 [  97231]   INFO - m.provider.JaxrsClientProvider - Successfully created an authenticated client? true 
2016-06-27 22:50:43,597 [  99067]   INFO - .auth.pat.VstsPatAuthenticator - Retrieving PersonalAccessToken for uri:https://app.vssps.visualstudio.com with name:VSTS IntelliJ Plugin: someone@mail.com from: computer on: Mon Jun 27 22:50:43 CEST 2016, and with scope:vso.build vso.build_execute vso.code vso.code_manage vso.code_write vso.work vso.work_write, prompt behavior: AUTO 
2016-06-27 22:50:44,169 [  99639]   INFO - tion.VsoAuthenticationProvider - getAuthenticationInfoAsync succeeded 
2016-06-27 22:50:47,119 [ 102589]  ERROR - ugin.authentication.AuthHelper - getAuthenticationInfoSynchronously: failed to get authentication info from user 
2016-06-27 22:50:47,120 [ 102590]   WARN - ugin.authentication.AuthHelper - getAuthenticationInfoSynchronously 
java.util.concurrent.ExecutionException: com.microsoft.alm.plugin.context.rest.VstsHttpClient$VstsHttpClientException: Unauthorized
    at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
    at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:272)
    at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:96)
    at com.microsoft.alm.plugin.authentication.AuthHelper.getAuthenticationInfoSynchronously(AuthHelper.java:90)
    at com.microsoft.alm.plugin.idea.extensions.TfGitHttpAuthDataProvider.getAuthData(TfGitHttpAuthDataProvider.java:39)
    at git4idea.commands.GitHttpGuiAuthenticator.findBestAuthData(GitHttpGuiAuthenticator.java:252)
    at git4idea.commands.GitHttpGuiAuthenticator.askUsername(GitHttpGuiAuthenticator.java:122)
    at git4idea.commands.GitHttpAuthService$InternalRequestHandlerDelegate.askUsername(GitHttpAuthService.java:62)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.jetbrains.ide.XmlRpcServerImpl.a(XmlRpcServerImpl.java:197)
    at org.jetbrains.ide.XmlRpcServerImpl.a(XmlRpcServerImpl.java:158)
    at org.jetbrains.ide.XmlRpcServerImpl.process(XmlRpcServerImpl.java:113)
    at org.jetbrains.ide.XmlRpcServerImpl$XmlRpcRequestHandler.process(XmlRpcServerImpl.java:72)
    at org.jetbrains.io.DelegatingHttpRequestHandler.checkAndProcess(DelegatingHttpRequestHandler.java:48)
    at org.jetbrains.io.DelegatingHttpRequestHandler.process(DelegatingHttpRequestHandler.java:68)
    at org.jetbrains.io.DelegatingHttpRequestHandlerBase.messageReceived(DelegatingHttpRequestHandlerBase.java:32)
    at org.jetbrains.io.DelegatingHttpRequestHandlerBase.messageReceived(DelegatingHttpRequestHandlerBase.java:25)
    at org.jetbrains.io.SimpleChannelInboundHandlerAdapter.channelRead0(SimpleChannelInboundHandlerAdapter.java:20)
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
    at io.netty.handler.codec.http.cors.CorsHandler.channelRead(CorsHandler.java:69)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:277)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:264)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
    at org.jetbrains.io.PortUnificationServerHandler.decode(PortUnificationServerHandler.java:141)
    at org.jetbrains.io.PortUnificationServerHandler.messageReceived(PortUnificationServerHandler.java:88)
    at org.jetbrains.io.Decoder.channelRead(Decoder.java:38)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:1078)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:117)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:527)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:484)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:398)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:370)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.microsoft.alm.plugin.context.rest.VstsHttpClient$VstsHttpClientException: Unauthorized
    at com.microsoft.alm.plugin.context.rest.VstsHttpClient.sendRequest(VstsHttpClient.java:34)
    at com.microsoft.alm.plugin.context.ServerContextManager.checkVstsConnection(ServerContextManager.java:204)
    at com.microsoft.alm.plugin.context.ServerContextManager.validateServerConnection(ServerContextManager.java:192)
    at com.microsoft.alm.plugin.authentication.VsoAuthenticationProvider$1.onSuccess(VsoAuthenticationProvider.java:79)
    at com.microsoft.alm.plugin.authentication.VsoAuthenticationProvider$1.onSuccess(VsoAuthenticationProvider.java:65)
    at com.google.common.util.concurrent.Futures$6.run(Futures.java:1319)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457)
    at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
    at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
    at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185)
    at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:53)
    at com.microsoft.alm.plugin.authentication.facades.VsoAuthInfoProvider$1.run(VsoAuthInfoProvider.java:134)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    ... 1 more
2016-06-27 22:50:47,413 [ 102883]   INFO -  #git4idea.commands.GitHandler - fatal: Authentication failed for 'https://xxx.visualstudio.com/DefaultCollection/_git/ng2-crud-app/' 
2016-06-27 22:50:47,415 [ 102885]   INFO -  #git4idea.commands.GitHandler - git push took 35411 ms. Command parameters: 
/usr/bin/git -c core.quotepath=false push --progress --porcelain origin refs/heads/master:master 
2016-06-27 22:50:47,424 [ 102894]   INFO -  #git4idea.commands.GitHandler - [ng2-crud-app] git -c core.quotepath=false push --progress --porcelain origin refs/heads/master:master 
2016-06-27 22:50:48,013 [ 103483]   INFO - ugin.authentication.AuthHelper - getAuthenticationInfoSynchronously calling authenticateAsync on https://xxx.visualstudio.com 
2016-06-27 22:50:48,013 [ 103483]   INFO - .auth.pat.VstsPatAuthenticator - Signing out from uri: https://app.vssps.visualstudio.com 
2016-06-27 22:50:48,013 [ 103483]   INFO - m.provider.JaxrsClientProvider - Getting a jaxrs client that works across multiple accounts. 
2016-06-27 22:50:48,014 [ 103484]   INFO - auth.oauth.OAuth2Authenticator - Using oauth2-useragent providers to retrieve AAD token. 
2016-06-27 22:51:04,856 [ 120326]  ERROR - auth.oauth.OAuth2Authenticator - Failed to launch oauth2-useragent. 
2016-06-27 22:51:04,856 [ 120326]   WARN - auth.oauth.OAuth2Authenticator - Failed to launch oauth2-useragent. 
com.microsoft.alm.oauth2.useragent.AuthorizationException: Code: cancelled Description: The browser window was closed by the user.
    at com.microsoft.alm.oauth2.useragent.AuthorizationResponse.fromString(AuthorizationResponse.java:109)
    at com.microsoft.alm.oauth2.useragent.UserAgentImpl.encode(UserAgentImpl.java:190)
    at com.microsoft.alm.oauth2.useragent.UserAgentImpl.requestAuthorizationCode(UserAgentImpl.java:150)
    at com.microsoft.alm.auth.oauth.AzureAuthority.acquireAuthorizationCode(AzureAuthority.java:249)
    at com.microsoft.alm.auth.oauth.AzureAuthority.acquireToken(AzureAuthority.java:190)
    at com.microsoft.alm.auth.oauth.OAuth2Authenticator$1.doRetrieve(OAuth2Authenticator.java:172)
    at com.microsoft.alm.auth.oauth.OAuth2Authenticator$1.doRetrieve(OAuth2Authenticator.java:161)
    at com.microsoft.alm.auth.BaseAuthenticator$SecretRetriever.retrieve(BaseAuthenticator.java:207)
    at com.microsoft.alm.auth.oauth.OAuth2Authenticator.getOAuth2TokenPair(OAuth2Authenticator.java:214)
    at com.microsoft.alm.provider.JaxrsClientProvider.getClient(JaxrsClientProvider.java:103)
    at com.microsoft.alm.provider.JaxrsClientProvider.getClient(JaxrsClientProvider.java:72)
    at com.microsoft.alm.plugin.authentication.facades.VsoAuthInfoProvider$1.run(VsoAuthInfoProvider.java:99)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
2016-06-27 22:51:04,856 [ 120326]   INFO - m.provider.JaxrsClientProvider - Successfully created an authenticated client? false 
2016-06-27 22:51:04,857 [ 120327]  ERROR - tion.VsoAuthenticationProvider - getAuthenticationInfoAsync failed 
com.microsoft.alm.oauth2.useragent.AuthorizationException: Code: Failed to get authenticated jaxrs client.
    at com.microsoft.alm.plugin.authentication.facades.VsoAuthInfoProvider$1.run(VsoAuthInfoProvider.java:136)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
2016-06-27 22:51:04,858 [ 120328]   INFO - .auth.pat.VstsPatAuthenticator - Signing out from uri: https://app.vssps.visualstudio.com 
2016-06-27 22:51:04,858 [ 120328]  ERROR - ugin.authentication.AuthHelper - getAuthenticationInfoSynchronously: failed to get authentication info from user 
2016-06-27 22:51:04,858 [ 120328]   WARN - ugin.authentication.AuthHelper - getAuthenticationInfoSynchronously 
java.util.concurrent.ExecutionException: com.microsoft.alm.oauth2.useragent.AuthorizationException: Code: Failed to get authenticated jaxrs client.
    at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
    at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:272)
    at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:96)
    at com.microsoft.alm.plugin.authentication.AuthHelper.getAuthenticationInfoSynchronously(AuthHelper.java:90)
    at com.microsoft.alm.plugin.idea.extensions.TfGitHttpAuthDataProvider.getAuthData(TfGitHttpAuthDataProvider.java:39)
    at git4idea.commands.GitHttpGuiAuthenticator.findBestAuthData(GitHttpGuiAuthenticator.java:252)
    at git4idea.commands.GitHttpGuiAuthenticator.askUsername(GitHttpGuiAuthenticator.java:122)
    at git4idea.commands.GitHttpAuthService$InternalRequestHandlerDelegate.askUsername(GitHttpAuthService.java:62)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.jetbrains.ide.XmlRpcServerImpl.a(XmlRpcServerImpl.java:197)
    at org.jetbrains.ide.XmlRpcServerImpl.a(XmlRpcServerImpl.java:158)
    at org.jetbrains.ide.XmlRpcServerImpl.process(XmlRpcServerImpl.java:113)
    at org.jetbrains.ide.XmlRpcServerImpl$XmlRpcRequestHandler.process(XmlRpcServerImpl.java:72)
    at org.jetbrains.io.DelegatingHttpRequestHandler.checkAndProcess(DelegatingHttpRequestHandler.java:48)
    at org.jetbrains.io.DelegatingHttpRequestHandler.process(DelegatingHttpRequestHandler.java:68)
    at org.jetbrains.io.DelegatingHttpRequestHandlerBase.messageReceived(DelegatingHttpRequestHandlerBase.java:32)
    at org.jetbrains.io.DelegatingHttpRequestHandlerBase.messageReceived(DelegatingHttpRequestHandlerBase.java:25)
    at org.jetbrains.io.SimpleChannelInboundHandlerAdapter.channelRead0(SimpleChannelInboundHandlerAdapter.java:20)
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
    at io.netty.handler.codec.http.cors.CorsHandler.channelRead(CorsHandler.java:69)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:277)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:264)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
    at org.jetbrains.io.PortUnificationServerHandler.decode(PortUnificationServerHandler.java:141)
    at org.jetbrains.io.PortUnificationServerHandler.messageReceived(PortUnificationServerHandler.java:88)
    at org.jetbrains.io.Decoder.channelRead(Decoder.java:38)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:1078)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:117)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:527)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:484)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:398)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:370)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.microsoft.alm.oauth2.useragent.AuthorizationException: Code: Failed to get authenticated jaxrs client.
    at com.microsoft.alm.plugin.authentication.facades.VsoAuthInfoProvider$1.run(VsoAuthInfoProvider.java:136)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
```

**Comment by leantk** [comment]
Hi Tim,

I'm sorry that you are having some trouble. Thanks for bringing it to our attention though. I'm assuming you are trying to create a pull request with our plugin and the push to the master branch failed. The top of the log is missing so that's why I'm asking to be sure I have the right idea of what is failing for you. 

Also some additional information that would be helpful:
* Did you clone this repo from the command line or did you clone using the plugin?
* If you go to this URL (replace xxx with your account) and sign in, do you see your account info or an unauthorized error? Use an incognito window so you don't use cached creds. https://xxx.visualstudio.com/DefaultCollection/_apis/connectionData?connectOptions=lastChangeId%3D-1&lastChangeId64=-1&api-version=1.0
* The second time the login window popped up, did you enter your credentials again or close the window? If you closed the window, try entering in your credentials again and see the behavior. If you could send me that additional logging too that could give me some more insight into what is going on.
* Are you able to see work items and pull requests in the Version Control tab at the bottom of the IDE? If you failed to sign in there, please send those logs as well.

Since this is an authentication issue, if you are uncomfortable discussing it here please feel free to email me instead at leantk@microsoft.com.

Thanks,
-Leah

**Comment by jpricketMSFT** [comment]
Closing due to no response
