### ISSUE TITLE
Can't obtain updateLastError method for class com.sun.jna.Native

### ISSUE THREAD

**Issue by miguelpiza93** [Microsoft/vso-intellij#2]
Trying to connect tfs' repository

Can't obtain updateLastError method for class com.sun.jna.Native
java.lang.UnsatisfiedLinkError: Can't obtain updateLastError method for class com.sun.jna.Native
	at com.sun.jna.Native.initIDs(Native Method)
	at com.sun.jna.Native.<clinit>(Native.java:139)
	at com.sun.jna.Pointer.<clinit>(Pointer.java:41)
	at com.sun.jna.PointerType.<init>(PointerType.java:25)
	at com.sun.jna.ptr.ByReference.<init>(ByReference.java:30)
	at com.sun.jna.ptr.IntByReference.<init>(IntByReference.java:22)
	at com.sun.jna.platform.win32.Secur32Util.getUserNameEx(Secur32Util.java:51)
	at org.apache.http.impl.auth.win.CurrentWindowsCredentials.getCurrentUsername(CurrentWindowsCredentials.java:60)
	at com.microsoft.alm.plugin.authentication.TfsAuthenticationProvider.getCredentials(TfsAuthenticationProvider.java:114)
	at com.microsoft.alm.plugin.authentication.TfsAuthenticationProvider.authenticateAsync(TfsAuthenticationProvider.java:58)
	at com.microsoft.alm.plugin.idea.ui.checkout.TfsCheckoutPageModel.loadRepositories(TfsCheckoutPageModel.java:93)
	at com.microsoft.alm.plugin.idea.ui.checkout.CheckoutPageController.actionPerformed(CheckoutPageController.java:87)
	at com.microsoft.alm.plugin.idea.ui.controls.Hyperlink.notifyActionListeners(Hyperlink.java:93)
	at com.microsoft.alm.plugin.idea.ui.controls.Hyperlink.access$000(Hyperlink.java:26)
	at com.microsoft.alm.plugin.idea.ui.controls.Hyperlink$1.linkSelected(Hyperlink.java:36)
	at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:106)
	at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:300)
	at com.intellij.ui.components.labels.LinkLabel$MyMouseHandler.mouseReleased(LinkLabel.java:277)
	at java.awt.Component.processMouseEvent(Component.java:6516)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3320)
	at java.awt.Component.processEvent(Component.java:6281)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:708)
	at java.awt.EventQueue$4.run(EventQueue.java:706)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:154)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:182)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:221)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:219)
	at java.awt.Dialog.show(Dialog.java:1082)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:778)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:465)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1614)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1571)
	at com.intellij.openapi.ui.DialogWrapper.showAndGet(DialogWrapper.java:1578)
	at com.microsoft.alm.plugin.idea.ui.common.BaseDialogImpl.showModalDialog(BaseDialogImpl.java:168)
	at com.microsoft.alm.plugin.idea.ui.checkout.CheckoutController.showModalDialog(CheckoutController.java:65)
	at com.microsoft.alm.plugin.idea.extensions.GitCheckoutProvider.doCheckout(GitCheckoutProvider.java:33)
	at com.intellij.openapi.vcs.checkout.CheckoutAction.actionPerformed(CheckoutAction.java:37)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:312)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:282)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:109)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:512)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:44)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:532)
	at java.awt.Component.processMouseEvent(Component.java:6516)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3320)
	at java.awt.Component.processEvent(Component.java:6281)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:708)
	at java.awt.EventQueue$4.run(EventQueue.java:706)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by leantk** [comment]
What version of Windows and IntelliJ are you using? I'm going to try and reproduce the error on our end.

**Comment by leantk** [comment]
And what version of Java are you using as well?

**Comment by miguelpiza93** [comment]
I'm working with Windows 7 x64, Android Studio 1.4. I'm using Java 1.7 because it's required for compile sdk version 23.

**Comment by leantk** [comment]
I'm still trying to reproduce your scenario but as I work on that, maybe you could try one thing for me if you don't mind. I found some similar issues where the same JNA exception was being thrown and it looks like it might be a JNA version issue. Can you try passing the argument described in this solution please: https://github.com/java-native-access/jna/issues/281

**Comment by miguelpiza93** [comment]
I'm working on java-native-access/jna#281 but not yet successful

**Comment by leantk** [comment]
Are you building the plugin using gradle or did you install the plugin through the Android Studio repo?

Also all signs at the moment seem to be pointing to the wrong jna version being picked up. I found a solution that I think will work but I'm still trying to recreate the error first before I have you try something that might not actually fix your problem.

**Comment by miguelpiza93** [comment]
I installed plugin through the Android Studio repo.

A few minutes ago, I downloaded IntelliJ Community Edition version 14 (but I need work in Android Studio), and I installed plugin through the repo and work. I set credentials but don't load repositories, the error message is "Lookup operation was canceled by the user", and I refresh but the same message appears.

If I can send more information about exception with Android Studio ask me. In IntelliJ, What could be the problem? Apparently, no exception occurs.

**Comment by leantk** [comment]
Thanks for the information. Let me ask you a few more questions so I understand correctly. For the IntelliJ problem, you got further with the plugin than you did in Android Studio correct? In both scenarios, were you trying to Checkout a project from VSO/TFS? You were able to sign in with IntelliJ but then saw the error you mentioned but in Android Studio you didn't even get to sign in right? Are you using TFS or VSO?

**Comment by miguelpiza93** [comment]
Yes, in both scenarios I'm trying to Checkout a project from VSO/TFS, and you are right, I'm able to sign in with IntelliJ but then see the other error. In Android Studio you didn't even get to sign in. And I'm  using TFS.

**Comment by leantk** [comment]
I still can't reproduce the Android jna issue but it looks like you can set your own vmoptions if you create a local vmoptions file. Do you already have a local vmoptions file? It would be in the directory <Users>\.<Android Studio version>\ and named studio.exe.vmoptions or studio64.exe.vmoptions. More details on that file are here if my instructions are unclear: http://tools.android.com/tech-docs/configuration

If you create that file (or open it if it already exists) and add "-Djna.nosys=true" as a line and save it, try again to use the plugin. If that still doesn't work we can set it to point to a specific jna jar but before we do that I want to see if option alone works.

**Comment by miguelpiza93** [comment]
I created two files, studio.exe.vmoptions and studio64.exe.vmoptions, in path specified in http://tools.android.com/tech-docs/configuration but still the plugin don't work

**Comment by leantk** [comment]
Ok thanks for trying. I'm going to focus on reproducing the error some more instead of bothering you with solutions that may not work. Can you give me the specific Java 7 version you are using and Android Studio release (i.e. jdk1.7.0_x, and 141.xxxxx). Maybe there is something in a specific version that I'm missing.

As for the IntelliJ error. Does it consistently reproduce? You can never see your repos populated in the dialog correct? Are you using the same jdk for IntelliJ that you are for Android Studio? The plugin is the exact same for both so I'm trying to see why you could log in for one application and not the other. If you did anything special for setting up either one that you can think of could you please let me know?

**Comment by leantk** [comment]
And one more thing, could you please paste the contents of this file: <Where you installed Android Studio>\Android Studio\bin\studio64.exe.vmoptions (i.e. C:\Program Files\Android\Android Studio\bin\studio64.exe.vmoptions)

**Comment by miguelpiza93** [comment]
As for IntelliJ error, I've never seen repos. And Only difference betwen Android Studio and Intellij is jdk for Intellij is jre1.8.0_51

I'm using jdk1.7.0_72 and Android Studio 141.2288178

The studio64.exe.vmoptions file's content is

#
# *DO NOT* modify this file directly. If there is a value that you would like to override,
# please add it to your user specific configuration file.
#
# See http://tools.android.com/tech-docs/configuration
#
-Xms256m
-Xmx1280m
-XX:MaxPermSize=350m
-XX:ReservedCodeCacheSize=225m
-XX:+UseConcMarkSweepGC
-XX:SoftRefLRUPolicyMSPerMB=50
-da
-Djna.nosys=true
-Djna.boot.library.path=

-Djna.debug_load=true
-Djna.debug_load.jna=true
-Dsun.io.useCanonCaches=false
-Djava.net.preferIPv4Stack=true
-Didea.paths.selector=AndroidStudio1.4
-Didea.platform.prefix=AndroidStudio

**Comment by leantk** [comment]
Miguel I sent you an email at a hotmail account I saw associated with you. I hope you don't mind. I was thinking I could send you a debug version of the plugin to help pinpoint the issue. Just let me know if that works for you. Thanks!

**Comment by madhurig** [comment]
We have a fix for the JNA issue in a new version 0.91.1 of the plugin: https://plugins.jetbrains.com/plugin/7981?pr=idea. There is no support for TFS 2013 with this plugin yet. Please consider creating a suggestion on user voice: https://visualstudio.uservoice.com/forums/121579-visual-studio-2015/category/30925-team-foundation-server-visual-studio-online
