### ISSUE TITLE
SSL handshake failure on authentication against Team Services using corporate ADFS

### ISSUE THREAD

**Issue by jtidmus** [Microsoft/vso-intellij#20]
**IDEA 2016.2 Plugin 1.103.0**
When signing-in against Team Services using "Work or school account" claims it is redirecting to the organisation's signin page but results in a failure due to SSL handshake error shown below and in the attached log (with debug enabled). 

The SSL certificate on the ADFS domain is valid and other clients can authenticate against it. Authentication works correctly using VSTS web portal and corporate ADFS.

**Log file:** [idea.log.txt](https://github.com/Microsoft/vso-intellij/files/393506/idea.log.txt)

**Extract:**

2016-08-01 09:55:00,697 [8317532]   INFO - m.provider.JaxrsClientProvider - Getting a jaxrs client that works across multiple accounts. 
2016-08-01 09:55:00,697 [8317532]  DEBUG - m.provider.JaxrsClientProvider - Getting a jaxrs client backed by OAuth2 token. 
2016-08-01 09:55:00,697 [8317532]  DEBUG - auth.oauth.OAuth2Authenticator - Retrieving OAuth2 TokenPair with prompt behavior: AUTO 
2016-08-01 09:55:00,697 [8317532]  DEBUG - oft.alm.auth.BaseAuthenticator - Getting secret for uri: https://app.vssps.visualstudio.com 
2016-08-01 09:55:00,697 [8317532]  DEBUG - om.microsoft.alm.secret.Secret - Secret::uriToName 
2016-08-01 09:55:00,697 [8317532]  DEBUG - om.microsoft.alm.secret.Secret -    target name = OAuth2:https://app.vssps.visualstudio.com 
2016-08-01 09:55:00,697 [8317532]  DEBUG - oft.alm.auth.BaseAuthenticator - Retrieving secret with key: OAuth2:https://app.vssps.visualstudio.com, and prompt behavior: AUTO. 
2016-08-01 09:55:00,697 [8317532]  DEBUG - oft.alm.auth.BaseAuthenticator - Reading secret from store for key: OAuth2:https://app.vssps.visualstudio.com 
2016-08-01 09:55:00,697 [8317532]  DEBUG - oft.alm.auth.BaseAuthenticator - Retrieving secret. 
2016-08-01 09:55:00,697 [8317532]  DEBUG - auth.oauth.OAuth2Authenticator - Ready to launch browser flow to retrieve oauth2 token. 
2016-08-01 09:55:00,697 [8317532]   INFO - auth.oauth.OAuth2Authenticator - Using oauth2-useragent providers to retrieve AAD token. 
2016-08-01 09:55:00,697 [8317532]  DEBUG - .alm.auth.oauth.AzureAuthority - AzureAuthority::acquireToken 
2016-08-01 09:55:17,461 [8334296]  ERROR - auth.oauth.OAuth2Authenticator - Failed to launch oauth2-useragent. 
2016-08-01 09:55:17,461 [8334296]   WARN - auth.oauth.OAuth2Authenticator - Failed to launch oauth2-useragent. 
com.microsoft.alm.oauth2.useragent.AuthorizationException: Code: load_error Description: java.lang.Throwable: SSL handshake failed
	at javafx.scene.web.WebEngine$LoadWorker.describeError(WebEngine.java:1436)
	at javafx.scene.web.WebEngine$LoadWorker.dispatchLoadEvent(WebEngine.java:1375)
	at javafx.scene.web.WebEngine$LoadWorker.access$1200(WebEngine.java:1253)
	at javafx.scene.web.WebEngine$PageLoadListener.dispatchLoadEvent(WebEngine.java:1240)
	at com.sun.webkit.WebPage.fireLoadEvent(WebPage.java:2400)
	at com.sun.webkit.WebPage.fwkFireLoadEvent(WebPage.java:2244)
	at com.sun.webkit.network.URLLoader.twkDidFail(Native Method)
	at com.sun.webkit.network.URLLoader.notifyDidFail(URLLoader.java:862)
	at com.sun.webkit.network.URLLoader.lambda$didFail$97(URLLoader.java:845)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)
	at com.microsoft.alm.oauth2.useragent.AuthorizationResponse.fromString(AuthorizationResponse.java:109)
	at com.microsoft.alm.oauth2.useragent.UserAgentImpl.encode(UserAgentImpl.java:190)
	at com.microsoft.alm.oauth2.useragent.UserAgentImpl.requestAuthorizationCode(UserAgentImpl.java:150)
	at com.microsoft.alm.auth.oauth.AzureAuthority.acquireAuthorizationCode(AzureAuthority.java:282)
	at com.microsoft.alm.auth.oauth.AzureAuthority.acquireToken(AzureAuthority.java:223)
	at com.microsoft.alm.auth.oauth.OAuth2Authenticator$1.doRetrieve(OAuth2Authenticator.java:181)
	at com.microsoft.alm.auth.oauth.OAuth2Authenticator$1.doRetrieve(OAuth2Authenticator.java:157)
	at com.microsoft.alm.auth.BaseAuthenticator$SecretRetriever.retrieve(BaseAuthenticator.java:217)
	at com.microsoft.alm.auth.oauth.OAuth2Authenticator.getOAuth2TokenPair(OAuth2Authenticator.java:208)
	at com.microsoft.alm.provider.JaxrsClientProvider.getClient(JaxrsClientProvider.java:103)
	at com.microsoft.alm.provider.JaxrsClientProvider.getClient(JaxrsClientProvider.java:72)
	at com.microsoft.alm.plugin.authentication.facades.VsoAuthInfoProvider$1.run(VsoAuthInfoProvider.java:127)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by yacaovsnc** [comment]
Thanks @jtidmus for reporting this issue.  Do you have a proxy in place and does that proxy server requires authentication?

**Comment by jtidmus** [comment]
@yacaovsnc No proxy but it looks like the ADFS uses a self-signed SSL certificate for internal users. Presumably, JavaFX cannot render this page causing the shown handshake failure. Does this seem like the likely explanation?

**Comment by yacaovsnc** [comment]
@jtidmus Yes, that does make sense -- Java by default can't establish secure connection with self-signed certs.   We need to instruct Java to trust the self signed cert either by import it to the default trust store, or create a new trust store and direct IntelliJ to use that.

I am a little bit confused, if you are connecting to VSTS,  I thought the site should be protected by our cert?   Are you connecting to a ****.visualstudio.com account or an on prem TFS instance?   

Thanks!

**Comment by jtidmus** [comment]
@yacaovsnc I can confirm that the workaround for the self-signed ADFS SSL certificate was to install the certificate chain into the JVM running IntelliJ. Then when attempting to access VSTS account at _*****.visualstudio.com_ the plugin is redirected to the corporate ADFS signin page at _adfs.*****.com_. The corporate self-signed certificate is accepted by the JavaFX renderer and the authentication completes successfully allowing the plugin to access the repos. 

Thanks for your help.

**Comment by yacaovsnc** [comment]
@jtidmus Glad you have found the workaround.  Thanks!
