### ISSUE TITLE
Unable to configure TFVC

### ISSUE THREAD

**Issue by cmckeegan** [Microsoft/vso-intellij#27]
Start Android studio, go into Preferences -> Version Control -> TFVC

Loading... spinner overlays over default txt and I get a notification that an error has occurred. Loading never completes.

[idea.log.zip](https://github.com/Microsoft/vso-intellij/files/520036/idea.log.zip)

**Comment by ayushindin** [comment]
+1 same bug

**Comment by jpricketMSFT** [comment]
Thanks for reporting this issue and providing your logs! I will take a look at this issue today. We hope to release several fixes this week.
Thanks,
Jason

**Comment by jpricketMSFT** [comment]
I am able to repro this with the "preview" version of the plugin. The logs don't indicate where in our code the problem is, but we have since updated the settings/preferences page for the plugin and that seems to have fixed the issue. You should see this problem go away with the next release. If not, please update this issue and let us know.

**Comment by jpricketMSFT** [comment]
I just realized that the release went out last night. So you should be able to update and get the fix. Please let us know if you still see an issue or if you don't see the TFVC settings page. (it has the location of the tf script to run).

**Comment by raviselvaraj** [comment]
I am still not been able to use the TFVC settings after the last night plugin update

Sorry I was not been able attache the log as zip file, see below:

2016-10-11 11:23:22,897 [ 183648]  ERROR - llij.ide.plugins.PluginManager - Android Studio 2.2.1  Build #AI-145.3330264 
2016-10-11 11:23:22,897 [ 183648]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_76-release 
2016-10-11 11:23:22,897 [ 183648]  ERROR - llij.ide.plugins.PluginManager - VM: OpenJDK 64-Bit Server VM 
2016-10-11 11:23:22,897 [ 183648]  ERROR - llij.ide.plugins.PluginManager - Vendor: JetBrains s.r.o 
2016-10-11 11:23:22,897 [ 183648]  ERROR - llij.ide.plugins.PluginManager - OS: Windows 8.1 
2016-10-11 11:23:22,897 [ 183648]  ERROR - llij.ide.plugins.PluginManager - Last Action: ShowSettings 
2016-10-11 11:23:23,512 [ 184263]  ERROR - til.concurrency.QueueProcessor - null 
java.lang.NullPointerException
	at com.microsoft.alm.plugin.idea.tfvc.core.TFSProjectConfigurable.isModified(TFSProjectConfigurable.java:44)
	at com.intellij.openapi.vcs.configurable.VcsManagerConfigurable$2.isModified(VcsManagerConfigurable.java:183)
	at com.intellij.openapi.options.newEditor.SettingsEditor.checkModifiedInternal(SettingsEditor.java:414)
	at com.intellij.openapi.options.newEditor.SettingsEditor.checkModifiedForItem(SettingsEditor.java:408)
	at com.intellij.openapi.options.newEditor.SettingsEditor.checkModified(SettingsEditor.java:392)
	at com.intellij.openapi.options.newEditor.SettingsEditor$5.updateCurrent(SettingsEditor.java:187)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor.updateIfCurrent(ConfigurableEditor.java:243)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor$4.run(ConfigurableEditor.java:200)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:333)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:323)
	at com.intellij.util.ui.update.MergingUpdateQueue$3.run(MergingUpdateQueue.java:267)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2440)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:279)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:234)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:378)
	at com.intellij.util.Alarm$Request.run(Alarm.java:398)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:227)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:792)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:465)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1661)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1610)
	at com.intellij.openapi.options.newEditor.SettingsDialog.access$001(SettingsDialog.java:41)
	at com.intellij.openapi.options.newEditor.SettingsDialog$1.run(SettingsDialog.java:80)
	at com.intellij.openapi.project.DumbPermissionServiceImpl.allowStartingDumbModeInside(DumbPermissionServiceImpl.java:37)
	at com.intellij.openapi.project.DumbService.allowStartingDumbModeInside(DumbService.java:283)
	at com.intellij.openapi.options.newEditor.SettingsDialog.show(SettingsDialog.java:77)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:94)
	at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:65)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:191)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:312)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:282)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:110)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:513)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:45)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:533)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2016-10-11 11:23:23,512 [ 184263]  ERROR - til.concurrency.QueueProcessor - Android Studio 2.2.1  Build #AI-145.3330264 
2016-10-11 11:23:23,512 [ 184263]  ERROR - til.concurrency.QueueProcessor - JDK: 1.8.0_76-release 
2016-10-11 11:23:23,512 [ 184263]  ERROR - til.concurrency.QueueProcessor - VM: OpenJDK 64-Bit Server VM 
2016-10-11 11:23:23,513 [ 184264]  ERROR - til.concurrency.QueueProcessor - Vendor: JetBrains s.r.o 
2016-10-11 11:23:23,513 [ 184264]  ERROR - til.concurrency.QueueProcessor - OS: Windows 8.1 
2016-10-11 11:23:23,513 [ 184264]  ERROR - til.concurrency.QueueProcessor - Last Action: ShowSettings 
2016-10-11 11:25:24,192 [ 304943]   INFO - in.events.ServerPollingManager - Timer fired 
2016-10-11 11:25:24,192 [ 304943]   INFO - ugin.events.ServerEventManager - triggering ALL events 
2016-10-11 11:25:24,192 [ 304943]   INFO - ugin.events.ServerEventManager - triggering event: BUILDS_CHANGED

**Comment by jpricketMSFT** [comment]
This callstack is a bit different than the others. It looks like a different issue, but we will look into it.
Thanks for reporting it and providing the logs.

**Comment by raviselvaraj** [comment]
+Attached log file

[idea.log.TXT](https://github.com/Microsoft/vso-intellij/files/522382/idea.log.TXT)

**Comment by leantk** [comment]
My apologize for the bug @raviselvaraj @cmckeegan @ayushindin. I just pushed version 1.107.1 of the plugin out which has the fix in it. Please let me know if that works for you. Thanks for reporting this!

**Comment by raviselvaraj** [comment]
Thank you @leantk for the quick response, New release worked.

**Comment by cmckeegan** [comment]
Thanks new release is working for me.

**Comment by DataworksPlusDev** [comment]
Having this issue now with Android Studio Hedgehog and Azure DevOps Plugin 1.162.2. Also cannot seem to get .\tf.cmd eula to execute and allow me to accept the agreement.
