### ISSUE TITLE
Proxy configuration in IntelliJ don't configure vso-intellij

### ISSUE THREAD

**Issue by carloreggiani** [Microsoft/vso-intellij#43]
I checked on the corporate proxy log the connection from IntelliJ and from the vso-intellij: it seems Intellij doesn't pass proxy configuration to the plugin! 

I think it is a bug: I didn't find any configuration option dedicated to the plugin.

I'm using the last version 1.101.7 of Visual Studio Team Services plugin.
Any workaround?

Thanks

Carlo

**Comment by jpricketMSFT** [comment]
Hi Carlo, 

Are you referring to the TFS Proxy or some other kind of proxy? We don't currently have support for TFS Proxies. We hope to have that support soon.

Thanks,
Jason

**Comment by carloreggiani** [comment]
Hi Jason

No no, I mean "normal" http/https proxy! 
I discover the problem checking the tcp connection by my pc using the plugin to connect a commit to a work item: the authentication not pass the proxy, but it is trying to connect directly to internet, failing :(

![intellij-vso1](https://cloud.githubusercontent.com/assets/1014429/20352105/59e6ff24-ac16-11e6-92d9-7c49b6944caf.jpg)

**Comment by jpricketMSFT** [comment]
Thanks for the clarification. We will look into this issue soon.

**Comment by hironico** [comment]
Apparently, un-authenticated proxies are supported according to the code in there : 
[JaxrsClientProvider](https://github.com/Microsoft/vsts-authentication-library-for-java/blob/master/providers/src/main/java/com/microsoft/alm/provider/JaxrsClientProvider.java)
at line 252.

Use the following environment variables: 
- http.proxyHost
- http.proxyPort

However, people (like me) behind authenticated proxies cannot use this plugin since there is no support for username and password.

So ... here you go ! :)

**Comment by yacaovsnc** [comment]
@hironico [#18](https://github.com/Microsoft/oauth2-useragent/issues/18)

If you are trying to connect to VSTS, authenticated proxy is not supported during oauth2 authentication process.  Once we are authenticated, we will use the credential to create a JAXRS client.   So it appears both places must support authenticated proxies.

**Comment by carloreggiani** [comment]
Hi @jpricketMSFT, any update?

**Comment by jpricketMSFT** [comment]
We are working on the proxy issues now. We hope to have them fixed soon and will release as soon as we have them in place.

Thanks,
Jason

**Comment by Dark-Hippo** [comment]
Hi @jpricketMSFT, was just wondering if there was any update on this?

I'm assessing the plugin for use within a reasonably sizeable project, and it's pretty much perfect, but at the moment this issue is proving a major stumbling block.

Thanks
Tom

**Comment by jpricketMSFT** [comment]
@Dark-Hippo - So, I am working on this right now :) 
We have a fix for On-Prem TFS servers, but it may not work with Hosted Team Services. Which are you targeting for this project?
Thanks,
Jason

**Comment by leantk** [comment]
We just released version 1.113.0 of the plugin which has support proxies set in the IDE. The settings page for this is in Preferences/Settings -> Appearance & Behavior -> System Settings -> HTTP Proxy. If you enter in your proxy info there the plugin will pick it up. Please let me know if this solves the issue for you.

**Comment by carloreggiani** [comment]
Hi @leantk , plugin updated in IntelliJ IDEA Community Edition 2016.3, corporate proxy configured and tested in IntelliJ settings, always the same error for login on Visual Studio Online to https://login.microsoftonline.com/common/oauth2/authorize?resource=.....

**Comment by leantk** [comment]
Hi @carloreggiani thanks for letting me know about the issue. Would you be able to send me a log please so I can see what exactly is happening in the background? You can follow the last FAQ at this link to get the log: http://java.visualstudio.com/Docs/tools/intelliJ#_frequently-asked-questions-faq
If you'd rather not post the log on here feel free to email it to me at leantk@microsoft.com.

Thanks,
-Leah

**Comment by carloreggiani** [comment]
Here the IDE Fatal Error info (I'm sendind the log to you):

`getAuthenticationInfoAsync failed: Failed to get authenticated jaxrs client.
com.microsoft.alm.oauth2.useragent.AuthorizationException: Code: Failed to get authenticated jaxrs client.
	at com.microsoft.alm.plugin.authentication.facades.VsoAuthInfoProvider.getAuthenticationInfoAsync(VsoAuthInfoProvider.java:153)
	at com.microsoft.alm.plugin.authentication.VsoAuthenticationProvider.authenticateAsync(VsoAuthenticationProvider.java:65)
	at com.microsoft.alm.plugin.idea.common.ui.common.LookupHelper.authenticateAndLoadVsoContexts(LookupHelper.java:158)
	at com.microsoft.alm.plugin.idea.common.ui.checkout.VsoCheckoutPageModel.loadRepositories(VsoCheckoutPageModel.java:76)
	at com.microsoft.alm.plugin.idea.common.ui.checkout.CheckoutPageController.actionPerformed(CheckoutPageController.java:92)
	at com.microsoft.alm.plugin.idea.common.ui.controls.Hyperlink.notifyActionListeners(Hyperlink.java:91)
	at com.microsoft.alm.plugin.idea.common.ui.controls.Hyperlink.access$000(Hyperlink.java:25)
	at com.microsoft.alm.plugin.idea.common.ui.controls.Hyperlink$1.linkSelected(Hyperlink.java:35)
	at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:156)
	at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:364)
	at com.intellij.ui.components.labels.LinkLabel$MyMouseHandler.mouseReleased(LinkLabel.java:341)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:675)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:779)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:457)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1693)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1635)
	at com.intellij.openapi.ui.DialogWrapper.showAndGet(DialogWrapper.java:1650)
	at com.microsoft.alm.plugin.idea.common.ui.common.BaseDialogImpl.showModalDialog(BaseDialogImpl.java:194)
	at com.microsoft.alm.plugin.idea.common.ui.checkout.CheckoutController.showModalDialog(CheckoutController.java:75)
	at com.microsoft.alm.plugin.idea.git.extensions.GitCheckoutProvider.doCheckout(GitCheckoutProvider.java:39)
	at com.intellij.openapi.vcs.checkout.CheckoutAction$1.run(CheckoutAction.java:39)
	at com.intellij.openapi.project.DumbPermissionServiceImpl.allowStartingDumbModeInside(DumbPermissionServiceImpl.java:37)
	at com.intellij.openapi.project.DumbService.allowStartingDumbModeInside(DumbService.java:294)
	at com.intellij.openapi.vcs.checkout.CheckoutAction.actionPerformed(CheckoutAction.java:34)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:199)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:215)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$2(ActionMenuItem.java:315)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:920)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:130)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:295)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:112)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:91)
	at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:41)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:116)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:126)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:112)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:513)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:45)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:533)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:675)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by leantk** [comment]
Since we fixed this offline I'm going to close the issue. If more help is needed though, please feel free to reopen this.

Thanks,
-Leah
