### ISSUE TITLE
Test tf executable failed when adding TFVC android studio plugin 

### ISSUE THREAD

**Issue by nanhapy** [Microsoft/vso-intellij#45]
1. i've download the "TEE-CLC-14.0.3.zip", and extract it
2. add tf executable path to environment variable
3. run `tf eula`, and enter `y` 
4. run `tf` successfully on command line, and output appears (...version 14.0.3...)
5. but test failed when  adding TFVC android studio plugin with alerts:

> The installed version of TF command line is 0.0.0. The minimum version suggested is 14.0.3.

Can everyone help me?

**Comment by leantk** [comment]
Hi @nanhapy 

Thanks for reporting your issue. Would you be able to attach your Android Studio log to this issue please? The log will show why the parsing we are doing for the version number isn't working. You can get the log by following the last FAQ here: http://java.visualstudio.com/Docs/tools/androidstudio#_frequently-asked-questions-faq

Sorry for the trouble,
-Leah

**Comment by mmajcica** [comment]
Hi @leantk,

I had a same issue as @nanhapy 

The only thing I do see in the log is the following:
```
2016-12-22 13:14:08,949 [  17642]   INFO - ugin.external.commands.Command - 167680800(ns) - elapsed time for add -noprompt -? 
2016-12-22 13:15:46,592 [ 115285]   INFO - lugin.external.ToolRunnerCache - getRunningToolRunner: toolLocation={0} 
2016-12-22 13:15:46,592 [ 115285]   INFO - lugin.external.ToolRunnerCache - getRunningToolRunner: slow version - null 
2016-12-22 13:15:46,592 [ 115285]   INFO - alm.plugin.external.ToolRunner - ToolRunner.start: toolLocation = C:\Program Files\TEE-CLC-14.0.3\tf.cmd 
2016-12-22 13:15:46,592 [ 115285]   INFO - alm.plugin.external.ToolRunner - ToolRunner.start: workingDirectory = null 
2016-12-22 13:15:46,592 [ 115285]   INFO - alm.plugin.external.ToolRunner - arguments: add -noprompt -? 
2016-12-22 13:15:46,716 [ 115409]   INFO - ugin.external.commands.Command - CMD: Error occurred during initialization of VM 
2016-12-22 13:15:46,717 [ 115410]   INFO - ugin.external.commands.Command - CMD: Could not reserve enough space for 2097152KB object heap 
2016-12-22 13:15:46,731 [ 115424]   WARN - ugin.external.commands.Command - CMD: parsing output failed 
com.microsoft.alm.plugin.external.exceptions.ToolBadExitCodeException: KEY_TF_BAD_EXIT_CODE
	at com.microsoft.alm.plugin.external.tools.TfTool.throwBadExitCode(TfTool.java:109)
	at com.microsoft.alm.plugin.external.commands.Command$1.completed(Command.java:155)
	at com.microsoft.alm.plugin.external.ToolRunner$ListenerProxy.completed(ToolRunner.java:289)
	at com.microsoft.alm.plugin.external.ToolRunner$ProcessWaiter.run(ToolRunner.java:327)
```

This was due to the heap memory. By default there in the tf.cmd you are starting the tool by requesting a heap of 2048MB. This is too much for certain machine (as in my case). I changed the -Xmx param to 512 and now is all working fine.

I hope this helps.

Mario

**Comment by leantk** [comment]
Hi @mmajcica,

Thanks so much for trying that out and letting us know the results! That is something that we can look into changing permanently or at least warn the users about and let them know a solution. I appreciate the help.

Happy holidays,
-Leah

**Comment by leantk** [comment]
@nanhapy,

If you are having the memory issue that @mmajcica described above, he solved it by opening the tf.cmd file (if on a Mac or Linux it would be the tf file). Look for the line that starts with "exec java -Xmx2048M" and change -Xmx2048M to -Xmx512M or at least a smaller size that is more suitable to your machine. Please let me know how this works for you.

Thanks,
-Leah

**Comment by mmajcica** [comment]
@leantk 

You are welcome. I would like to note also that I was running on Citrix and due to some limitations I went as far as setting it to 512. This however makes the plugin very, very slow. If possible a better, intermediate, option will be setting it to 1024M. Something user needs to try.

Cheers,
Mario

**Comment by jpricketMSFT** [comment]
It appears that this issue was fixed by adjusting the jvm options set in the tf.cmd file. Closing.

**Comment by Nerves82** [comment]
This fix no longer works. https://github.com/microsoft/azure-devops-intellij/issues/392
