### ISSUE TITLE
getAuthenticationInfoAsync failed

### ISSUE THREAD

**Issue by vapisar** [Microsoft/vso-intellij#493]
JetBrains Rider 2022.1.2 (Build #RD-221.5787.36, built on June 1, 2022) sometimes throws the following exception:
```
getAuthenticationInfoAsync failed

java.lang.Error: java.io.IOException: HTTP request failed with code 400: {"$id":"1","innerException":null,"message":"FullScopePatPolicyViolation","typeName":"Microsoft.VisualStudio.Services.DelegatedAuthorization.SessionTokenCreateException, Microsoft.VisualStudio.Services.WebApi, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","typeKey":"SessionTokenCreateException","errorCode":0,"eventId":3000}

	at com.microsoft.alm.auth.pat.VsoAzureAuthority.generatePersonalAccessToken(VsoAzureAuthority.java:79)
	at com.microsoft.alm.auth.pat.VstsPatAuthenticator$1.doRetrieve(VstsPatAuthenticator.java:195)
	at com.microsoft.alm.auth.pat.VstsPatAuthenticator$1.doRetrieve(VstsPatAuthenticator.java:157)
	at com.microsoft.alm.auth.BaseAuthenticator$SecretRetriever.retrieve(BaseAuthenticator.java:268)
	at com.microsoft.alm.auth.pat.VstsPatAuthenticator.getToken(VstsPatAuthenticator.java:202)
	at com.microsoft.alm.auth.pat.VstsPatAuthenticator.getPersonalAccessToken(VstsPatAuthenticator.java:142)
	at com.microsoft.alm.plugin.authentication.facades.VsoAuthInfoProvider.getAuthenticationInfo(VsoAuthInfoProvider.java:138)
	at com.microsoft.alm.plugin.authentication.facades.VsoAuthInfoProvider.getAuthenticationInfoAsync(VsoAuthInfoProvider.java:95)
	at com.microsoft.alm.plugin.authentication.VsoAuthenticationProvider.authenticateAsync(VsoAuthenticationProvider.java:66)
	at com.microsoft.alm.plugin.authentication.AuthHelper.getAuthenticationInfoSynchronously(AuthHelper.java:59)
	at com.microsoft.alm.plugin.context.ServerContextManager.getAuthenticationInfo(ServerContextManager.java:504)
	at com.microsoft.alm.plugin.context.ServerContextManager.getAuthenticationInfo(ServerContextManager.java:480)
	at com.microsoft.alm.plugin.context.ServerContextManager.createContextFromGitRemoteUrl(ServerContextManager.java:366)
	at com.microsoft.alm.plugin.context.ServerContextManager.createContextFromGitRemoteUrl(ServerContextManager.java:347)
	at com.microsoft.alm.plugin.context.ServerContextManager.getAuthenticatedContext(ServerContextManager.java:327)
	at com.microsoft.alm.plugin.context.ServerContextManager.getUpdatedContext(ServerContextManager.java:597)
	at com.microsoft.alm.plugin.operations.PullRequestLookupOperation$1.run(PullRequestLookupOperation.java:73)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: HTTP request failed with code 400: {"$id":"1","innerException":null,"message":"FullScopePatPolicyViolation","typeName":"Microsoft.VisualStudio.Services.DelegatedAuthorization.SessionTokenCreateException, Microsoft.VisualStudio.Services.WebApi, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","typeKey":"SessionTokenCreateException","errorCode":0,"eventId":3000}

	at com.microsoft.alm.helpers.HttpClientImpl.ensureOK(HttpClientImpl.java:41)
	at com.microsoft.alm.helpers.HttpClientImpl.getPostResponseText(HttpClientImpl.java:186)
	at com.microsoft.alm.auth.pat.VsoAzureAuthority.generatePersonalAccessToken(VsoAzureAuthority.java:69)
	... 21 more
```

**Comment by jonmclean** [comment]
I received the same error using PyCharm 2022.3.1 and the latest available plugin version.  I received the error when I open the Tasks tab and tried to list my DevOps tasks.  This was a fresh install of the plugin.

`getAuthenticationInfoAsync failed

java.lang.Error: java.io.IOException: HTTP request failed with code 400: {"$id":"1","innerException":null,"message":"FullScopePatPolicyViolation","typeName":"Microsoft.VisualStudio.Services.DelegatedAuthorization.SessionTokenCreateException, Microsoft.VisualStudio.Services.WebApi, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","typeKey":"SessionTokenCreateException","errorCode":0,"eventId":3000}

	at com.microsoft.alm.auth.pat.VsoAzureAuthority.generatePersonalAccessToken(VsoAzureAuthority.java:79)
	at com.microsoft.alm.auth.pat.VstsPatAuthenticator$1.doRetrieve(VstsPatAuthenticator.java:195)
	at com.microsoft.alm.auth.pat.VstsPatAuthenticator$1.doRetrieve(VstsPatAuthenticator.java:157)
	at com.microsoft.alm.auth.BaseAuthenticator$SecretRetriever.retrieve(BaseAuthenticator.java:268)
	at com.microsoft.alm.auth.pat.VstsPatAuthenticator.getToken(VstsPatAuthenticator.java:202)
	at com.microsoft.alm.auth.pat.VstsPatAuthenticator.getPersonalAccessToken(VstsPatAuthenticator.java:142)
	at com.microsoft.alm.plugin.authentication.facades.VsoAuthInfoProvider.getAuthenticationInfo(VsoAuthInfoProvider.java:138)
	at com.microsoft.alm.plugin.authentication.facades.VsoAuthInfoProvider.getAuthenticationInfoAsync(VsoAuthInfoProvider.java:95)
	at com.microsoft.alm.plugin.authentication.VsoAuthenticationProvider.authenticateAsync(VsoAuthenticationProvider.java:66)
	at com.microsoft.alm.plugin.authentication.AuthHelper.getAuthenticationInfoSynchronously(AuthHelper.java:59)
	at com.microsoft.alm.plugin.context.ServerContextManager.getAuthenticationInfo(ServerContextManager.java:504)
	at com.microsoft.alm.plugin.context.ServerContextManager.getAuthenticationInfo(ServerContextManager.java:480)
	at com.microsoft.alm.plugin.context.ServerContextManager.createContextFromGitRemoteUrl(ServerContextManager.java:366)
	at com.microsoft.alm.plugin.context.ServerContextManager.createContextFromGitRemoteUrl(ServerContextManager.java:347)
	at com.microsoft.alm.plugin.context.ServerContextManager.getAuthenticatedContext(ServerContextManager.java:327)
	at com.microsoft.alm.plugin.context.ServerContextManager.getUpdatedContext(ServerContextManager.java:587)
	at com.microsoft.alm.plugin.operations.Operation$1.run(Operation.java:185)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.IOException: HTTP request failed with code 400: {"$id":"1","innerException":null,"message":"FullScopePatPolicyViolation","typeName":"Microsoft.VisualStudio.Services.DelegatedAuthorization.SessionTokenCreateException, Microsoft.VisualStudio.Services.WebApi, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","typeKey":"SessionTokenCreateException","errorCode":0,"eventId":3000}

	at com.microsoft.alm.helpers.HttpClientImpl.ensureOK(HttpClientImpl.java:41)
	at com.microsoft.alm.helpers.HttpClientImpl.getPostResponseText(HttpClientImpl.java:186)
	at com.microsoft.alm.auth.pat.VsoAzureAuthority.generatePersonalAccessToken(VsoAzureAuthority.java:69)
	... 21 more
`

**Comment by Lopfest** [comment]
I'm having the same issue. Installed the plugin, popup authentication appeared, followed the steps and this error came in.
So I cannot use this plugin at all.

**Comment by connorjs** [comment]
I recommend closing issues related to `FullScopePatPolicyViolation` in favor of #481 which, at time of writing, has the most up votes. Let's focus the discussion there.
