### ISSUE TITLE
OAuth 2.0 Authorization Request error

### ISSUE THREAD

**Issue by nikgibbens** [Microsoft/vso-intellij#555]
When doing a `git push` or trying to get work items using the Azure DevOps plugin 1.162.1 for JetBrains PyCharm Professional 2023.1 

PyCharm 2023.1 (Professional Edition)
Build #PY-231.8109.197, built on March 29, 2023
Licensed to Nik Gibbens
Subscription is active until January 1, 2024.
Runtime version: 17.0.6+10-b829.5 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.microsoft.vso.idea (1.162.1)
    ru.adelf.idea.dotenv (2023.1)

MacOS Ventura 13.3.1 (22E261)

I get the following stack exception:

```
getAuthenticationInfoAsync failed

com.microsoft.alm.client.model.VssResourceNotFoundException: API resource location f83735dc-483f-4238-a291-d45f6080a9af is not registered on https://app.vssps.visualstudio.com. HTTP 400 Bad Request
	at com.microsoft.alm.client.AlmHttpClientBase.createTarget(AlmHttpClientBase.java:138)
	at com.microsoft.alm.client.AlmHttpClientBase.createRequest(AlmHttpClientBase.java:463)
	at com.microsoft.alm.client.AlmHttpClientBase.createRequest(AlmHttpClientBase.java:334)
	at com.microsoft.visualstudio.services.account.AccountHttpClient.getMyProfile(AccountHttpClient.java:49)
	at com.microsoft.alm.plugin.authentication.facades.VsoAuthInfoProvider.getAuthenticationInfo(VsoAuthInfoProvider.java:123)
	at com.microsoft.alm.plugin.authentication.facades.VsoAuthInfoProvider.getAuthenticationInfoAsync(VsoAuthInfoProvider.java:95)
	at com.microsoft.alm.plugin.authentication.VsoAuthenticationProvider.authenticateAsync(VsoAuthenticationProvider.java:66)
	at com.microsoft.alm.plugin.authentication.AuthHelper.getAuthenticationInfoSynchronously(AuthHelper.java:59)
	at com.microsoft.alm.plugin.context.ServerContextManager.getAuthenticationInfo(ServerContextManager.java:504)
	at com.microsoft.alm.plugin.context.ServerContextManager.getAuthenticationInfo(ServerContextManager.java:480)
	at com.microsoft.alm.plugin.context.ServerContextManager.createContextFromGitRemoteUrl(ServerContextManager.java:366)
	at com.microsoft.alm.plugin.context.ServerContextManager.createContextFromGitRemoteUrl(ServerContextManager.java:347)
	at com.microsoft.alm.plugin.context.ServerContextManager.getAuthenticatedContext(ServerContextManager.java:327)
	at com.microsoft.alm.plugin.context.ServerContextManager.getUpdatedContext(ServerContextManager.java:587)
	at com.microsoft.alm.plugin.operations.PullRequestLookupOperation$1.run(PullRequestLookupOperation.java:73)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: javax.ws.rs.BadRequestException: HTTP 400 Bad Request
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1053)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:859)
	at org.glassfish.jersey.client.JerseyInvocation.access$500(JerseyInvocation.java:75)
	at org.glassfish.jersey.client.JerseyInvocation$2.completed(JerseyInvocation.java:816)
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:203)
	at org.glassfish.jersey.client.ClientRuntime.access$200(ClientRuntime.java:61)
	at org.glassfish.jersey.client.ClientRuntime$2.lambda$response$0(ClientRuntime.java:154)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:288)
	at org.glassfish.jersey.client.ClientRuntime$2.response(ClientRuntime.java:154)
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:480)
	at org.glassfish.jersey.client.ClientRuntime.lambda$null$3(ClientRuntime.java:163)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:288)
	at org.glassfish.jersey.client.ClientRuntime.lambda$createRunnableForAsyncProcessing$4(ClientRuntime.java:139)
	... 5 more
```

However, if I go to the terminal and do a `git push` on the command line, everything works.

**Comment by ForNeVeR** [comment]
If everything works from the terminal, either remove the plugin or enable the system credential helper support (in the Git settings in the IDE, I think):
<img width="633" alt="image" src="https://user-images.githubusercontent.com/92793/235118903-365b6979-6dfe-4272-be24-3e3d2daf40f6.png">
