### ISSUE TITLE
Error on startup in IntelliJ

### ISSUE THREAD

**Issue by Lugribossk** [Microsoft/vso-intellij#592]
Every time I start IntelliJ I get this error:
```
java.lang.Throwable: com.microsoft.alm.plugin.context.ServerContextManager$Holder <clinit> requests com.microsoft.alm.plugin.idea.common.settings.TeamServicesSecrets instance. Class initialization must not depend on services. Consider using instance of the service on-demand instead.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.serviceContainer.ComponentManagerImplKt.checkOutsideClassInitializer(ComponentManagerImpl.kt:1588)
	at com.intellij.serviceContainer.ComponentManagerImplKt.getOrCreateInstanceBlocking(ComponentManagerImpl.kt:1557)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:746)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:690)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:23)
	at com.microsoft.alm.plugin.idea.common.settings.TeamServicesSecrets.getInstance(TeamServicesSecrets.java:23)
	at com.microsoft.alm.plugin.idea.common.settings.TeamServicesSettingsService.restoreServerContexts(TeamServicesSettingsService.java:75)
	at com.microsoft.alm.plugin.idea.common.services.ServerContextStoreImpl.restoreServerContexts(ServerContextStoreImpl.java:25)
	at com.microsoft.alm.plugin.context.ServerContextManager.restoreFromSavedState(ServerContextManager.java:178)
	at com.microsoft.alm.plugin.context.ServerContextManager.<init>(ServerContextManager.java:71)
	at com.microsoft.alm.plugin.context.ServerContextManager$Holder.<clinit>(ServerContextManager.java:55)
	at com.microsoft.alm.plugin.context.ServerContextManager.getInstance(ServerContextManager.java:79)
	at com.microsoft.alm.plugin.operations.Operation.getServerContext(Operation.java:164)
	at com.microsoft.alm.plugin.operations.BuildStatusLookupOperation.doWork(BuildStatusLookupOperation.java:149)
	at com.microsoft.alm.plugin.operations.OperationExecutor$1.run(OperationExecutor.java:56)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```
IntelliJ version 2024.2 and Azure DevOps plugin version 1.162.2

**Comment by bobonov** [comment]
Same error in PhpStorm 2024.2.4, today update Build #PS-242.23726.107, built on October 23, 2024

**Comment by Lugribossk** [comment]
Is anything happening with this or is this plugin effectively abandoned?
