### ISSUE TITLE
Plugin doesn't work under authenticated proxy.

### ISSUE THREAD

**Issue by wawyed** [Microsoft/vso-intellij#89]
I have set up WebStorm proxy correctly via PAC file, unfortunately when trying to sign in with VSTS the login is screen is blank, letting me believe that is not going through the proxy.

![image](https://user-images.githubusercontent.com/4390806/28204681-e6618826-6876-11e7-9ce6-24126d3a2592.png)

![image](https://user-images.githubusercontent.com/4390806/28204704-f8e58e2a-6876-11e7-89b9-0f31eccc01db.png)

**Comment by leantk** [comment]
Hi @wawyed,

Thanks for reporting the issue. Could you do 2 things for me please?

1) Try authenticating with Device Flow. Sometimes the browser experience has been flaky for people so that's why we added device flow. You can enable that by going to File -> Settings -> Version Control -> Team Services / TFS. Select Device flow under the Authentication Method section. Try to login again and see if that works for you.

2) Could you please send me a log from WebStorm? We have logging that shows if the proxy is being picked up so I want to see what is going wrong. You can follow the last FAQ here to turn on debugging and find the log: http://java.visualstudio.com/Docs/tools/intelliJ#_frequently-asked-questions-faq

You can either attach the log here or email it to me at leantk@microsoft.com.

Thanks,
-Leah

**Comment by RedaMehali** [comment]
Hi @leantk 
I had a similar error where I got prompted with key_credentials_error. This happened using Android Studio and TFVC plugin. I opened a thread on StackOverFlow. Here is the link: https://stackoverflow.com/questions/48568844/commit-failed-with-unknown-error-commiting-changes-to-vs-using-tfvc-plugin

Thanks.

**Comment by vladonemo** [comment]
I'm facing this issue now, too.

**Comment by ForNeVeR** [comment]
@vladonemo have you tried setting up the Device Flow as adviced earlier?

**Comment by vladonemo** [comment]
@ForNeVeR yep, just tried again. I receive the exception below. I believe that the bug is in the microsoft's VsoAuthInfoProvider. It doesn't use proxy settings anywhere. It makes a direct call and fails on timeout.

```
getAuthenticationInfoAsync failed

com.microsoft.alm.client.model.VssResourceNotFoundException: API resource location f83735dc-483f-4238-a291-d45f6080a9af is not registered on https://app.vssps.visualstudio.com. org.apache.http.conn.HttpHostConnectException: Connect to app.vssps.visualstudio.com:443 [app.vssps.visualstudio.com/13.107.6.175] failed: Connection timed out: connect
	at com.microsoft.alm.client.AlmHttpClientBase.createTarget(AlmHttpClientBase.java:138)
	at com.microsoft.alm.client.AlmHttpClientBase.createRequest(AlmHttpClientBase.java:463)
	at com.microsoft.alm.client.AlmHttpClientBase.createRequest(AlmHttpClientBase.java:334)
	at com.microsoft.visualstudio.services.account.AccountHttpClient.getMyProfile(AccountHttpClient.java:49)
	at com.microsoft.alm.plugin.authentication.facades.VsoAuthInfoProvider.getAuthenticationInfo(VsoAuthInfoProvider.java:123)
	at com.microsoft.alm.plugin.authentication.facades.VsoAuthInfoProvider.getAuthenticationInfoAsync(VsoAuthInfoProvider.java:95)
	at com.microsoft.alm.plugin.authentication.VsoAuthenticationProvider.authenticateAsync(VsoAuthenticationProvider.java:69)
	at com.microsoft.alm.plugin.authentication.AuthHelper.getAuthenticationInfoSynchronously(AuthHelper.java:59)
	at com.microsoft.alm.plugin.context.ServerContextManager.getAuthenticationInfo(ServerContextManager.java:481)
	at com.microsoft.alm.plugin.context.ServerContextManager.createContextFromGitRemoteUrl(ServerContextManager.java:364)
	at com.microsoft.alm.plugin.context.ServerContextManager.createContextFromGitRemoteUrl(ServerContextManager.java:345)
	at com.microsoft.alm.plugin.context.ServerContextManager.getAuthenticatedContext(ServerContextManager.java:325)
	at com.microsoft.alm.plugin.context.ServerContextManager.getUpdatedContext(ServerContextManager.java:555)
	at com.microsoft.alm.plugin.operations.Operation$1.run(Operation.java:184)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.ws.rs.ProcessingException: org.apache.http.conn.HttpHostConnectException: Connect to app.vssps.visualstudio.com:443 [app.vssps.visualstudio.com/13.107.6.175] failed: Connection timed out: connect
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:472)
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:479)
	at org.glassfish.jersey.client.ClientRuntime.lambda$null$3(ClientRuntime.java:163)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:288)
	at org.glassfish.jersey.client.ClientRuntime.lambda$createRunnableForAsyncProcessing$4(ClientRuntime.java:139)
	... 5 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to app.vssps.visualstudio.com:443 [app.vssps.visualstudio.com/13.107.6.175] failed: Connection timed out: connect
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:426)
	... 14 more
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:337)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
	... 23 more
```

**Comment by ForNeVeR** [comment]
Well maybe it shouldn't try to use proxy explicitly. You have set up the proxy settings in IDEA configuration, right?

**Comment by vladonemo** [comment]
yes, I have everything else (that needs connection) works. But after you wrote I played around with the proxy settings and got it to work! 
We use Auto-detect proxy settings with a proxy configuration URL. Switching that to manual proxy settings (specifying the HTTP proxy URL and port explicitly) it works. It is acceptable as a workaround I'd say. But not very convenient, as I'd need to switch on/off proxy manually everytime I connect direct/via proxy.

Anyway, thanks for the help ;)

**Comment by ForNeVeR** [comment]
Okay, thanks for info: it means that the VCS client has troubles with proxy auto-detection for some reason.

**Comment by msilb** [comment]
I have experienced the same issue just now connecting via our corporate proxy. Login using proxy auto-detect setting doesn't work but the workaround of specifying the proxy url manually works fine and I'm able to log in.
