### ISSUE TITLE
Unable to log in to Team Services

### ISSUE THREAD

**Issue by Excelzn** [Microsoft/vso-intellij#98]
I get the error "Unable to authenticate to Team Services. Verify your network connection and credentials and try again" consistently every time I try and sign in. Log file is attached.
[idea.txt](https://github.com/Microsoft/vso-intellij/files/1233239/idea.txt)

**Comment by leantk** [comment]
Hi @Excelzn,

It looks like you are having issues authenticating when you try to get a token from AAD. Does it look like you successfully enter in your credentials in the pop-up browser? Are you able to login through a browser normally? If so, try changing to device flow as your authentication method. You can do that by going to File -> Settings -> Version Control -> Team Services / TFS. Under Authentication Method select Device Flow and try to log in again and see if you see any difference.

![image](https://user-images.githubusercontent.com/13628312/29617633-7d717452-87e3-11e7-8b4f-90c50b9b8563.png)

Thanks,
-Leah

**Comment by legiami** [comment]
I got the same error (using PHPStorm) even using "device flow".
I can login using browser normally. I try to clear all credential, change password, etc. Nothing works.

Error after authenticating using "device flow"
```
getAuthenticationInfoAsync failed: Unexpected exception type: Microsoft.VisualStudio.Services.Common.VssServiceException, Microsoft.VisualStudio.Services.Common
java.lang.AssertionError: Unexpected exception type: Microsoft.VisualStudio.Services.Common.VssServiceException, Microsoft.VisualStudio.Services.Common
	at com.microsoft.alm.client.model.WrappedException.Unwrap(WrappedException.java:186)
	at com.microsoft.alm.client.AlmHttpClientBase.handleResponse(AlmHttpClientBase.java:536)
	at com.microsoft.alm.client.AlmHttpClientBase.sendRequest(AlmHttpClientBase.java:508)
	at com.microsoft.alm.client.AlmHttpClientBase.sendRequest(AlmHttpClientBase.java:518)
	at com.microsoft.visualstudio.services.account.AccountHttpClient.getMyProfile(AccountHttpClient.java:55)
	at com.microsoft.alm.plugin.authentication.facades.VsoAuthInfoProvider.getAuthenticationInfo(VsoAuthInfoProvider.java:123)
	at com.microsoft.alm.plugin.authentication.facades.VsoAuthInfoProvider.getAuthenticationInfoAsync(VsoAuthInfoProvider.java:95)
	at com.microsoft.alm.plugin.authentication.VsoAuthenticationProvider.authenticateAsync(VsoAuthenticationProvider.java:69)
	at com.microsoft.alm.plugin.authentication.AuthHelper.getAuthenticationInfoSynchronously(AuthHelper.java:59)
	at com.microsoft.alm.plugin.context.ServerContextManager.getAuthenticationInfo(ServerContextManager.java:488)
	at com.microsoft.alm.plugin.context.ServerContextManager.createContextFromGitRemoteUrl(ServerContextManager.java:372)
	at com.microsoft.alm.plugin.context.ServerContextManager.createContextFromGitRemoteUrl(ServerContextManager.java:353)
	at com.microsoft.alm.plugin.context.ServerContextManager.getAuthenticatedContext(ServerContextManager.java:333)
	at com.microsoft.alm.plugin.context.ServerContextManager.getUpdatedContext(ServerContextManager.java:562)
	at com.microsoft.alm.plugin.operations.PullRequestLookupOperation$1.run(PullRequestLookupOperation.java:73)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by leantk** [comment]
@legiami could you attach the whole log please? That looks a little different from what's in the first log you attached. Thanks!

**Comment by legiami** [comment]
@leantk this is last log file [idea.txt](https://github.com/Microsoft/vso-intellij/files/1245811/idea.txt)

**Comment by Excelzn** [comment]
That actually worked for me. Thanks.

**Comment by leantk** [comment]
Hi @legiami it looks like we are having an issue getting your profile while logging you in and that's why it's failing. Would you be able to email me the account URL you are trying to use, the email address associated with that account, and an approximate date/time of the last time you tried this and it failed? I'm going to look at your requests logged in our system and see why they failed in more detail.

My email address is leantk@microsoft.com

Thanks,
-Leah

**Comment by legiami** [comment]
@leantk I send mail to you. Today everything is working - maybe you have some old data in cache (in plugin or in visualstudio.com)? I don't use account in last week.

**Comment by leantk** [comment]
Thanks for letting me know @legiami and I'm glad to hear its all working for you now. I'll close this issue as resolved then but if you have any more issues please feel free to reopen it.

**Comment by Gruwa** [comment]
HI, i have same error

![image](https://user-images.githubusercontent.com/22069739/44278469-b9080d80-a256-11e8-8f98-be154eeea386.png)

![image](https://user-images.githubusercontent.com/22069739/44278362-70e8eb00-a256-11e8-9eed-f28aa1450697.png)

![image](https://user-images.githubusercontent.com/22069739/44278720-a3471800-a257-11e8-80d1-57d4a968e963.png)


`com.microsoft.alm.plugin.external.exceptions.ToolException: KEY_TF_EXE_NOT_FOUND
	at com.microsoft.alm.plugin.external.tools.TfTool.getValidLocation(TfTool.java:77)
	at com.microsoft.alm.plugin.external.commands.Command.run(Command.java:139)
	at com.microsoft.alm.plugin.external.commands.Command.runSynchronously(Command.java:216)
	at com.microsoft.alm.plugin.idea.tfvc.ui.checkout.TfvcCheckoutModel$1.run(TfvcCheckoutModel.java:80)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:736)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

ty`

What do I do wrong?

**Comment by shivra198** [comment]
Is this issue resolved? I am also facing the same issue..

**Comment by ForNeVeR** [comment]
@shivra198, yes, the issue has been marked resolved. There're multiple various problems stated in the opening post and in the comments, so from your message it is unclear what exact problem you're having.

Could you please make sure you use the latest version of the plugin and open a new issue?

**Comment by shbhmpthk** [comment]
I am also facing the same issue in any type of login. can someone help here please

**Comment by ForNeVeR** [comment]
@shbhmpthk, from your message it is unclear what exact problem you're having.

Could you please make sure you use the latest version of the plugin and open a new issue with more detailed explanation?
